CREATE TABLE REPLY
(
	BOARD_NO NUMBER NOT NULL,
	REPLY_NO NUMBER NOT NULL,
	WRITER VARCHAR2(64) NOT NULL,
	CONTENT VARCHAR2(100) NOT NULL,
	POSTDATE DATE,
	IP VARCHAR2(64) NOT NULL,
	
	CONSTRAINT REPLY_PK PRIMARY KEY(BOARD_NO, REPLY_NO)
);

CREATE SEQUENCE REPLY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
